import { type ChangeEvent, type FormEvent, type ReactNode, useEffect, useState } from 'react';
import { exportProfileJson, importProfileJson } from '../profile/profile-json';
import { createEmptyProfile, type UserProfile } from '../profile/schema';
import { loadProfile, saveProfile } from '../storage/profile-storage';
import { DEFAULT_AI_SETTINGS, loadAISettings, saveAISettings, type AISettings } from '../storage/ai-settings';
import { addEducation, addFamilyMember, addInternship, addLanguage, addProject, removeCollectionItem, removeEducation, setHighestEducation, updateEducation, type CollectionKey } from './profile-editor';

type BasicKey=keyof UserProfile['basic'];
export function App(){
 const [profile,setProfile]=useState<UserProfile>(createEmptyProfile);const [ai,setAI]=useState<AISettings>(DEFAULT_AI_SETTINGS);const [ready,setReady]=useState(false);const [status,setStatus]=useState('正在读取本地资料…');
 useEffect(()=>{Promise.all([loadProfile(),loadAISettings()]).then(([value,settings])=>{setProfile(value);setAI(settings);setStatus('');}).catch(()=>setStatus('读取资料失败，请重新打开设置页。')).finally(()=>setReady(true));},[]);
 function updateBasic(key:BasicKey,value:string){setProfile(current=>({...current,basic:{...current.basic,[key]:value}}));}
 function updateList(key:Exclude<CollectionKey,'educations'>,id:string,patch:Record<string,string>){setProfile(current=>({...current,[key]:current[key].map(item=>item.id===id?{...item,...patch}:item)} as UserProfile));}
 async function handleSubmit(event:FormEvent){event.preventDefault();setStatus('正在保存…');try{const saved=await saveProfile(profile);await saveAISettings(ai);setProfile(saved);setStatus('资料与 AI 设置已保存在当前浏览器本地。');}catch(error){setStatus(error instanceof Error?error.message:'保存失败，请检查输入。');}}
 async function handleImport(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;try{setProfile(importProfileJson(await file.text()));setStatus('JSON 已导入，请检查后保存。');}catch(error){setStatus(error instanceof Error?error.message:'导入失败。');}finally{event.target.value='';}}
 function handleExport(){try{const blob=new Blob([exportProfileJson(profile)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='profile.v2.json';link.click();URL.revokeObjectURL(url);setStatus('已导出最新版本 Profile。');}catch(error){setStatus(error instanceof Error?error.message:'导出失败。');}}
 return <main className='page'><header><p className='eyebrow'>AI Job Application Assistant</p><h1>个人资料</h1><p className='intro'>所有资料仅保存在 chrome.storage.local。扩展不会自动提交申请。</p><div className='import-export'><label className='file-button'>导入 JSON<input type='file' accept='application/json,.json' onChange={handleImport}/></label><button type='button' className='secondary' onClick={handleExport}>导出 JSON</button></div></header><form onSubmit={handleSubmit}>
 <section><h2>基本信息</h2><div className='grid'><Field label='姓名'><input value={profile.basic.fullName} onChange={e=>updateBasic('fullName',e.target.value)}/></Field><Field label='性别'><select value={profile.basic.gender} onChange={e=>updateBasic('gender',e.target.value)}><option value=''>请选择</option><option value='male'>男</option><option value='female'>女</option><option value='other'>其他</option><option value='prefer_not_to_say'>不愿透露</option></select></Field><Field label='手机号'><input type='tel' value={profile.basic.phone} onChange={e=>updateBasic('phone',e.target.value)}/></Field><Field label='邮箱'><input type='email' value={profile.basic.email} onChange={e=>updateBasic('email',e.target.value)}/></Field><Field label='出生日期'><input type='date' value={profile.basic.birthDate} onChange={e=>updateBasic('birthDate',e.target.value)}/></Field><Field label='城市'><input value={profile.basic.city} onChange={e=>updateBasic('city',e.target.value)}/></Field><Field label='所在地区'><input value={profile.basic.region} onChange={e=>updateBasic('region',e.target.value)}/></Field></div></section>
 <Section title='教育经历' onAdd={()=>setProfile(addEducation(profile))} addLabel='添加教育经历'>{profile.educations.map((item,index)=><Card key={item.id} title={`${item.school||`教育经历 ${index+1}`}${item.degree?` · ${item.degree}`:''}`} onDelete={()=>setProfile(removeEducation(profile,item.id))}><div className='grid'><Field label='学校名称'><input value={item.school} onChange={e=>setProfile(updateEducation(profile,item.id,{school:e.target.value}))}/></Field><Field label='学院/院系'><input value={item.college} onChange={e=>setProfile(updateEducation(profile,item.id,{college:e.target.value}))}/></Field><Field label='学历'><input value={item.degree} onChange={e=>setProfile(updateEducation(profile,item.id,{degree:e.target.value}))}/></Field><Field label='专业'><input value={item.major} onChange={e=>setProfile(updateEducation(profile,item.id,{major:e.target.value}))}/></Field><Field label='入学时间'><input type='month' value={item.startDate} onChange={e=>setProfile(updateEducation(profile,item.id,{startDate:e.target.value}))}/></Field><Field label='毕业时间'><input type='month' value={item.endDate} onChange={e=>setProfile(updateEducation(profile,item.id,{endDate:e.target.value}))}/></Field><Field label='最高学历'><input type='checkbox' checked={item.isHighest} onChange={e=>setProfile(e.target.checked?setHighestEducation(profile,item.id):updateEducation(profile,item.id,{isHighest:false}))}/></Field></div></Card>)}</Section>
 <Section title='实习经历' onAdd={()=>setProfile(addInternship(profile))} addLabel='添加实习经历'>{profile.internships.map((item,index)=><Card key={item.id} title={`${item.company||`实习经历 ${index+1}`}${item.position?` · ${item.position}`:''}`} onDelete={()=>setProfile(removeCollectionItem(profile,'internships',item.id))}><div className='grid'><Text label='公司' value={item.company} set={company=>updateList('internships',item.id,{company})}/><Text label='部门' value={item.department} set={department=>updateList('internships',item.id,{department})}/><Text label='职位' value={item.position} set={position=>updateList('internships',item.id,{position})}/><Text label='城市' value={item.city} set={city=>updateList('internships',item.id,{city})}/><Text label='开始时间' type='month' value={item.startDate} set={startDate=>updateList('internships',item.id,{startDate})}/><Text label='结束时间' type='month' value={item.endDate} set={endDate=>updateList('internships',item.id,{endDate})}/><TextArea label='描述' value={item.description} set={description=>updateList('internships',item.id,{description})}/></div></Card>)}</Section>
 <Section title='项目经历' onAdd={()=>setProfile(addProject(profile))} addLabel='添加项目经历'>{profile.projects.map((item,index)=><Card key={item.id} title={`${item.name||`项目经历 ${index+1}`}${item.role?` · ${item.role}`:''}`} onDelete={()=>setProfile(removeCollectionItem(profile,'projects',item.id))}><div className='grid'><Text label='项目名称' value={item.name} set={name=>updateList('projects',item.id,{name})}/><Text label='角色' value={item.role} set={role=>updateList('projects',item.id,{role})}/><Text label='开始时间' type='month' value={item.startDate} set={startDate=>updateList('projects',item.id,{startDate})}/><Text label='结束时间' type='month' value={item.endDate} set={endDate=>updateList('projects',item.id,{endDate})}/><TextArea label='描述' value={item.description} set={description=>updateList('projects',item.id,{description})}/></div></Card>)}</Section>
 <Section title='语言能力' onAdd={()=>setProfile(addLanguage(profile))} addLabel='添加语言能力'>{profile.languages.map((item,index)=><Card key={item.id} title={item.language||`语言能力 ${index+1}`} onDelete={()=>setProfile(removeCollectionItem(profile,'languages',item.id))}><div className='grid'><Text label='语言' value={item.language} set={language=>updateList('languages',item.id,{language})}/><Text label='熟练程度' value={item.proficiency} set={proficiency=>updateList('languages',item.id,{proficiency})}/><Text label='证书' value={item.certificate} set={certificate=>updateList('languages',item.id,{certificate})}/><Text label='成绩' value={item.score} set={score=>updateList('languages',item.id,{score})}/></div></Card>)}</Section>
 <Section title='家庭成员' onAdd={()=>setProfile(addFamilyMember(profile))} addLabel='添加家庭成员'>{profile.familyMembers.map((item,index)=><Card key={item.id} title={`${item.relationship||`家庭成员 ${index+1}`}${item.name?` · ${item.name}`:''}`} onDelete={()=>setProfile(removeCollectionItem(profile,'familyMembers',item.id))}><div className='grid'><Text label='与本人关系' value={item.relationship} set={relationship=>updateList('familyMembers',item.id,{relationship})}/><Text label='姓名' value={item.name} set={name=>updateList('familyMembers',item.id,{name})}/><Text label='出生日期' type='date' value={item.birthDate} set={birthDate=>updateList('familyMembers',item.id,{birthDate})}/><Text label='工作单位' value={item.employer} set={employer=>updateList('familyMembers',item.id,{employer})}/><Text label='职务' value={item.position} set={position=>updateList('familyMembers',item.id,{position})}/><Text label='联系电话' type='tel' value={item.phone} set={phone=>updateList('familyMembers',item.id,{phone})}/></div></Card>)}</Section>
 <section><h2>求职意向</h2><div className='grid'><Field label='求职方向（逗号分隔）'><input value={profile.jobPreferences.directions.join(', ')} onChange={e=>setProfile(current=>({...current,jobPreferences:{...current.jobPreferences,directions:splitList(e.target.value)}}))}/></Field><Field label='期望城市（逗号分隔）'><input value={profile.jobPreferences.preferredCities.join(', ')} onChange={e=>setProfile(current=>({...current,jobPreferences:{...current.jobPreferences,preferredCities:splitList(e.target.value)}}))}/></Field></div></section>
 <section><h2>Optional AI Semantic Fallback</h2><p className='intro'>默认关闭；Profile 内容不会发送，AI 建议必须人工确认。</p><div className='grid'><Field label='启用 AI 语义识别'><input type='checkbox' checked={ai.enabled} onChange={e=>setAI(current=>({...current,enabled:e.target.checked}))}/></Field><Field label='Provider ID'><input value={ai.providerId} onChange={e=>setAI(current=>({...current,providerId:e.target.value}))}/></Field><Field label='API Key（仅本地）'><input type='password' autoComplete='off' value={ai.apiKey} onChange={e=>setAI(current=>({...current,apiKey:e.target.value}))}/></Field></div></section>
 <div className='actions'><button type='submit' disabled={!ready}>保存到浏览器</button><span role='status' aria-live='polite'>{status}</span></div></form></main>;
}
function splitList(value:string){return value.split(/[,，]/).map(item=>item.trim()).filter(Boolean);}
function Section({title,onAdd,addLabel,children}:{title:string;onAdd:()=>void;addLabel:string;children:ReactNode}){return <section><h2>{title}</h2><div className='cards'>{children}</div><button type='button' className='add-button' onClick={onAdd}>＋ {addLabel}</button></section>;}
function Card({title,onDelete,children}:{title:string;onDelete:()=>void;children:ReactNode}){return <details className='card'><summary><strong>{title}</strong><span>展开/收起</span></summary><div className='card-body'>{children}<button type='button' className='danger' onClick={onDelete}>删除</button></div></details>;}
function Field({label,children}:{label:string;children:ReactNode}){return <label><span>{label}</span>{children}</label>;}
function Text({label,value,set,type='text'}:{label:string;value?:string;set:(value:string)=>void;type?:string}){return <Field label={label}><input type={type} value={value??''} onChange={e=>set(e.target.value)}/></Field>;}
function TextArea({label,value,set}:{label:string;value?:string;set:(value:string)=>void}){return <Field label={label}><textarea value={value??''} onChange={e=>set(e.target.value)}/></Field>;}
