import { type FormEvent, useEffect, useState } from "react";
import { createEmptyProfile, type UserProfile } from "../profile/schema";
import { loadProfile, saveProfile } from "../storage/profile-storage";
import { DEFAULT_AI_SETTINGS, loadAISettings, saveAISettings, type AISettings } from "../storage/ai-settings";
type BasicKey=keyof UserProfile["basic"];type EducationKey="school"|"college"|"degree"|"major"|"startDate"|"endDate";
export function App(){
 const [profile,setProfile]=useState<UserProfile>(createEmptyProfile);const [ai,setAI]=useState<AISettings>(DEFAULT_AI_SETTINGS);const [ready,setReady]=useState(false);const [status,setStatus]=useState("正在读取本地资料…");
 useEffect(()=>{Promise.all([loadProfile(),loadAISettings()]).then(([value,settings])=>{setProfile(value);setAI(settings);setStatus("");}).catch(()=>setStatus("读取资料失败，请重新打开设置页。")).finally(()=>setReady(true));},[]);
 function updateBasic(key:BasicKey,value:string){setProfile(current=>({...current,basic:{...current.basic,[key]:value}}));}
 function updateEducation(key:EducationKey,value:string){setProfile(current=>({...current,educations:[{...current.educations[0],[key]:value}]}));}
 async function handleSubmit(event:FormEvent){event.preventDefault();setStatus("正在保存…");try{const saved=await saveProfile(profile);await saveAISettings(ai);setProfile(saved);setStatus("资料与 AI 设置已保存在当前浏览器本地。");}catch(error){setStatus(error instanceof Error?error.message:"保存失败，请检查输入。");}}
 const education=profile.educations[0];return <main className="page"><header><p className="eyebrow">AI Job Application Assistant</p><h1>个人资料</h1><p className="intro">资料和可选 API Key 仅保存在浏览器本地。AI 默认关闭；扩展不会自动提交申请。</p></header><form onSubmit={handleSubmit}>
 <section><h2>基本信息</h2><div className="grid"><Field label="姓名"><input value={profile.basic.fullName} onChange={e=>updateBasic("fullName",e.target.value)}/></Field><Field label="性别"><select value={profile.basic.gender} onChange={e=>updateBasic("gender",e.target.value)}><option value="">请选择</option><option value="male">男</option><option value="female">女</option><option value="other">其他</option><option value="prefer_not_to_say">不愿透露</option></select></Field><Field label="手机号"><input type="tel" value={profile.basic.phone} onChange={e=>updateBasic("phone",e.target.value)}/></Field><Field label="邮箱"><input type="email" value={profile.basic.email} onChange={e=>updateBasic("email",e.target.value)}/></Field><Field label="出生日期"><input type="date" value={profile.basic.birthDate} onChange={e=>updateBasic("birthDate",e.target.value)}/></Field><Field label="城市"><input value={profile.basic.city} onChange={e=>updateBasic("city",e.target.value)}/></Field><Field label="所在地区"><input value={profile.basic.region} onChange={e=>updateBasic("region",e.target.value)}/></Field></div></section>
 <section><h2>最高教育经历</h2><div className="grid"><Field label="学校"><input value={education.school} onChange={e=>updateEducation("school",e.target.value)}/></Field><Field label="学院"><input value={education.college} onChange={e=>updateEducation("college",e.target.value)}/></Field><Field label="学历"><input value={education.degree} placeholder="例如：本科" onChange={e=>updateEducation("degree",e.target.value)}/></Field><Field label="专业"><input value={education.major} onChange={e=>updateEducation("major",e.target.value)}/></Field><Field label="入学时间"><input type="month" value={education.startDate} onChange={e=>updateEducation("startDate",e.target.value)}/></Field><Field label="毕业时间"><input type="month" value={education.endDate} onChange={e=>updateEducation("endDate",e.target.value)}/></Field></div></section>
 <section><h2>Optional AI Semantic Fallback</h2><p className="intro">默认关闭，仅处理 ambiguous/unmatched。Profile 内容不会发送；AI 建议必须手动勾选。当前仓库只提供 Provider 接口，不预装远程 Provider。</p><div className="grid"><Field label="启用 AI 语义识别"><input type="checkbox" checked={ai.enabled} onChange={e=>setAI(current=>({...current,enabled:e.target.checked}))}/></Field><Field label="Provider ID"><input value={ai.providerId} placeholder="由未来 Provider Adapter 提供" onChange={e=>setAI(current=>({...current,providerId:e.target.value}))}/></Field><Field label="API Key（仅本地）"><input type="password" autoComplete="off" value={ai.apiKey} onChange={e=>setAI(current=>({...current,apiKey:e.target.value}))}/></Field></div></section>
 <div className="actions"><button type="submit" disabled={!ready}>保存到浏览器</button><span role="status" aria-live="polite">{status}</span></div></form></main>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span>{label}</span>{children}</label>;}