import { mkdirSync, writeFileSync } from "node:fs";
import { loadCompatibilitySamples } from "../extension/core/evaluation/fixtures";
import { evaluateSamples, predictSample } from "../extension/core/evaluation/runner";
import { FakeAIProvider } from "../extension/core/semantic/fake-provider";
import { createSemanticInput, hybridMatchField } from "../extension/core/semantic/hybrid-matcher";
import { semanticCacheKey } from "../extension/core/semantic/cache";
import { ProviderSemanticMatcher } from "../extension/core/semantic/semantic-matcher";
import { SEMANTIC_ABLATIONS } from "../extension/core/semantic/ablation";
import type { SemanticMatchResult } from "../extension/core/semantic/types";

const samples=loadCompatibilitySamples();const ruleReport=evaluateSamples(samples);const fallbackIds=new Set(ruleReport.fallbackCases.map(item=>item.caseId));const fallbackSamples=samples.filter(item=>fallbackIds.has(item.caseId));
const scripted=new Map<string,SemanticMatchResult>();
fallbackSamples.forEach((sample,index)=>{const rule=predictSample(sample)!;const input=createSemanticInput(sample.descriptor!,rule);const second=input.availableProfilePaths.find(path=>path!==sample.expectedProfilePath)!;scripted.set(semanticCacheKey(input),index<fallbackSamples.length-1?{status:"matched",profilePath:sample.expectedProfilePath,confidence:.96,reasonCodes:["fake_fixture_semantic_match"],candidatePaths:[{profilePath:sample.expectedProfilePath!,confidence:.96},{profilePath:second,confidence:.65}]}:{status:"ambiguous",profilePath:sample.expectedProfilePath,confidence:.78,reasonCodes:["fake_insufficient_context"],candidatePaths:[{profilePath:sample.expectedProfilePath!,confidence:.78},{profilePath:second,confidence:.7}]});});
const provider=new FakeAIProvider(input=>scripted.get(semanticCacheKey(input))??{status:"unmatched",confidence:0,reasonCodes:["fake_no_fixture"],candidatePaths:[]});const matcher=new ProviderSemanticMatcher(provider);const outcomes=[];
for(const sample of fallbackSamples){const rule=predictSample(sample)!;const hybrid=await hybridMatchField(sample.descriptor!,rule,{enabled:true,matcher});outcomes.push({caseId:sample.caseId,descriptor:hybrid.aiResult?createSemanticInput(sample.descriptor!,rule).field:undefined,expected:sample.expectedProfilePath,aiPrediction:hybrid.aiResult?.profilePath,confidence:hybrid.aiResult?.confidence,status:hybrid.aiResult?.status,reasonCodes:hybrid.aiResult?.reasonCodes??[],candidates:hybrid.aiResult?.candidatePaths??[],hybridStatus:hybrid.hybridResult.status,hybridPath:hybrid.hybridResult.profilePath});}
const aiMatched=outcomes.filter(item=>item.status==="matched");const aiCorrect=aiMatched.filter(item=>item.aiPrediction===item.expected).length;const aiPrecision=aiMatched.length?aiCorrect/aiMatched.length:0;const aiRecall=outcomes.length?aiCorrect/outcomes.length:0;const aiF1=aiPrecision+aiRecall?2*aiPrecision*aiRecall/(aiPrecision+aiRecall):0;
const hybridAdded=outcomes.filter(item=>item.hybridStatus==="matched"&&item.hybridPath===item.expected).length;const hybridCorrect=ruleReport.metrics.correctMatches+hybridAdded;const hybridPredicted=ruleReport.metrics.correctMatches+ruleReport.metrics.wrongMatches+outcomes.filter(item=>item.hybridStatus==="matched").length;const expected=ruleReport.cases.filter(item=>item.expectedProfilePath).length;const hybridPrecision=hybridPredicted?hybridCorrect/hybridPredicted:0;const hybridRecall=hybridCorrect/expected;const hybridF1=2*hybridPrecision*hybridRecall/(hybridPrecision+hybridRecall);const wrong=hybridPredicted-hybridCorrect;
const summary={provider:"scripted-fake",disclaimer:"Pipeline validation only; not a measurement of any real AI model.",fallbackCases:outcomes.length,ai:{accuracy:aiCorrect/outcomes.length,precision:aiPrecision,recall:aiRecall,f1:aiF1,matched:aiMatched.length,ambiguous:outcomes.filter(item=>item.status==="ambiguous").length,wrong:aiMatched.length-aiCorrect},ruleOnly:ruleReport.metrics,hybrid:{precision:hybridPrecision,recall:hybridRecall,f1:hybridF1,wrongMatchRate:wrong/ruleReport.metrics.totalFields,correctMatches:hybridCorrect,wrongMatches:wrong},ablationFramework:{enabled:true,conclusion:"Dataset has only seven fallback cases; no model-quality conclusion is reported.",variants:SEMANTIC_ABLATIONS}};
mkdirSync("reports/ai",{recursive:true});writeFileSync("reports/ai/ai_wrong_matches.json",JSON.stringify(outcomes.filter(item=>item.status==="matched"&&item.aiPrediction!==item.expected),null,2)+"\n");writeFileSync("reports/ai/ai_ambiguous.json",JSON.stringify(outcomes.filter(item=>item.status!=="matched"),null,2)+"\n");writeFileSync("reports/ai/hybrid_evaluation.json",JSON.stringify(summary,null,2)+"\n");
const pct=(value:number)=>`${(value*100).toFixed(1)}%`;console.log("AI Semantic Fallback Evaluation (scripted fake provider)");console.log(`Fallback cases: ${outcomes.length}`);console.log(`AI fallback accuracy: ${pct(summary.ai.accuracy)}`);console.log(`AI fallback precision: ${pct(aiPrecision)}`);console.log(`AI fallback recall: ${pct(aiRecall)}`);console.log(`Hybrid precision: ${pct(hybridPrecision)}`);console.log(`Hybrid recall: ${pct(hybridRecall)}`);console.log(`Hybrid F1: ${pct(hybridF1)}`);console.log(`Hybrid wrong match rate: ${pct(summary.hybrid.wrongMatchRate)}`);