import { afterEach, describe, expect, it, vi } from "vitest";
import { OpenAICompatibleProvider, AIProviderError } from "../../extension/core/semantic/openai-compatible-provider";
import { ProviderSemanticMatcher } from "../../extension/core/semantic/semantic-matcher";
import type { SemanticMatchInput, SemanticMatchResult } from "../../extension/core/semantic/types";

const config={apiKey:"test-key-not-a-secret",baseUrl:"https://provider.invalid/v1",model:"test-model",timeoutMs:100};
const input:SemanticMatchInput={field:{kind:"text",labelTexts:["Candidate name"],visualLabelTexts:[],placeholder:"Enter name",name:"candidate_name",id:undefined,ariaLabel:undefined,legend:undefined,nearbyText:[],sectionTexts:["Basic"],options:[],inputType:"text"},candidates:[{profilePath:"basic.fullName",ruleConfidence:.72}],availableProfilePaths:["basic.fullName","basic.email"],sectionContext:["Basic"]};
const matched:SemanticMatchResult={status:"matched",profilePath:"basic.fullName",confidence:.96,reasonCodes:["semantic_label"],candidatePaths:[{profilePath:"basic.fullName",confidence:.96}]};
function completion(value:unknown,status=200){return new Response(JSON.stringify({choices:[{message:{content:typeof value==="string"?value:JSON.stringify(value)}}]}),{status,headers:{"Content-Type":"application/json"}});}
function provider(fetcher:typeof fetch){return new OpenAICompatibleProvider(config,fetcher);}

describe("OpenAICompatibleProvider",()=>{
 afterEach(()=>vi.restoreAllMocks());
 it("constructs a structured Chat Completions request from only SemanticMatchInput",async()=>{const fetcher=vi.fn(async(url:string|URL|Request,init?:RequestInit)=>{void url;void init;return completion(matched);});await provider(fetcher as typeof fetch).infer(input);expect(fetcher).toHaveBeenCalledOnce();const [url,init]=fetcher.mock.calls[0];expect(url).toBe("https://provider.invalid/v1/chat/completions");const body=JSON.parse(String(init?.body));expect(body.model).toBe("test-model");expect(body.response_format.type).toBe("json_schema");expect(body.response_format.json_schema.schema.properties.profilePath.enum).toEqual(input.availableProfilePaths);const sent=body.messages[1].content;expect(sent).toBe(JSON.stringify(input));expect(sent).not.toContain("UserProfile");expect(sent).not.toContain("PRIVATE_PROFILE_VALUE");});
 it("never writes the API key to console or an error",async()=>{const log=vi.spyOn(console,"log").mockImplementation(()=>{});const fetcher=vi.fn(async()=>new Response("denied",{status:401}));await expect(provider(fetcher as typeof fetch).infer(input)).rejects.toMatchObject({code:"invalid_api_key",message:"invalid_api_key"});expect(JSON.stringify(log.mock.calls)).not.toContain(config.apiKey);});
 it("parses a valid matched response",async()=>expect(new ProviderSemanticMatcher(provider((async()=>completion(matched)) as typeof fetch)).match(input)).resolves.toEqual(matched));
 it("parses a valid ambiguous response",async()=>{const ambiguous={status:"ambiguous",confidence:.62,reasonCodes:["insufficient_evidence"],candidatePaths:[{profilePath:"basic.fullName",confidence:.62}]};expect((await new ProviderSemanticMatcher(provider((async()=>completion(ambiguous)) as typeof fetch)).match(input)).status).toBe("ambiguous");});
 it("rejects an illegal profile path",async()=>{const invalid={...matched,profilePath:"private.secret",candidatePaths:[{profilePath:"private.secret",confidence:.96}]};await expect(new ProviderSemanticMatcher(provider((async()=>completion(invalid)) as typeof fetch)).match(input)).rejects.toThrow("invalid_semantic_profile_path");});
 it("rejects confidence outside zero to one",async()=>await expect(new ProviderSemanticMatcher(provider((async()=>completion({...matched,confidence:2})) as typeof fetch)).match(input)).rejects.toThrow("invalid_semantic_confidence"));
 it("rejects responses with missing required fields",async()=>await expect(new ProviderSemanticMatcher(provider((async()=>completion({status:"matched",confidence:.9})) as typeof fetch)).match(input)).rejects.toThrow("missing_semantic_profile_path"));
 it("rejects non-JSON model output",async()=>await expect(provider((async()=>completion("not json")) as typeof fetch).infer(input)).rejects.toEqual(new AIProviderError("invalid_response")));
 it("maps 401 to invalid_api_key",async()=>await expect(provider((async()=>new Response(null,{status:401})) as typeof fetch).infer(input)).rejects.toMatchObject({code:"invalid_api_key"}));
 it("maps 429 to rate_limited",async()=>await expect(provider((async()=>new Response(null,{status:429})) as typeof fetch).infer(input)).rejects.toMatchObject({code:"rate_limited"}));
 it("maps AbortError to provider_timeout",async()=>{const fetcher=vi.fn((_url:string|URL|Request,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener("abort",()=>reject(new DOMException("aborted","AbortError")))));await expect(new OpenAICompatibleProvider({...config,timeoutMs:1},fetcher as typeof fetch).infer(input)).rejects.toMatchObject({code:"provider_timeout"});});
 it("falls back to strict JSON parsing when json_schema is unsupported",async()=>{const fetcher=vi.fn().mockResolvedValueOnce(new Response("response_format json_schema unsupported",{status:400})).mockResolvedValueOnce(completion(matched));expect(await provider(fetcher as typeof fetch).infer(input)).toEqual(matched);expect(fetcher).toHaveBeenCalledTimes(2);expect(JSON.parse(String(fetcher.mock.calls[1][1]?.body))).not.toHaveProperty("response_format");});
});