import { describe, expect, it } from "vitest";
import { SemanticMatchCache } from "../../extension/core/semantic/cache";
import { FakeAIProvider } from "../../extension/core/semantic/fake-provider";
import { createSemanticInput, hybridMatchField } from "../../extension/core/semantic/hybrid-matcher";
import { AIProviderRegistry } from "../../extension/core/semantic/provider-registry";
import { ProviderSemanticMatcher } from "../../extension/core/semantic/semantic-matcher";
import type { SemanticMatchResult } from "../../extension/core/semantic/types";
import { defaultSelectedFieldIds } from "../../extension/popup/semantic-selection";
import type { FieldDescriptor } from "../../extension/core/scanner/types";
import type { MatchResult } from "../../extension/core/matcher/types";

function field(label="Candidate name"):FieldDescriptor{return {fieldId:"f1",kind:"text",attributes:{type:"text",name:"candidate_name",placeholder:"Enter value"},context:{labelTexts:[label],visualLabelTexts:[],ariaLabelledByTexts:[],legendText:undefined,sectionTexts:["Basic information"],nearbyText:[],parentText:label},options:[],state:{currentValue:"",required:false,disabled:false,readOnly:false,visible:true},safety:{excluded:false}};}
function rule(status:MatchResult["status"]="ambiguous"):MatchResult{return {fieldId:"f1",status,profilePath:status==="matched"?"basic.fullName":undefined,confidence:status==="matched"?.96:.72,evidence:[],candidatePaths:[{profilePath:"basic.fullName",confidence:.72},{profilePath:"basic.email",confidence:.2}]};}
function ai(overrides:Partial<SemanticMatchResult>={}):SemanticMatchResult{return {status:"matched",profilePath:"basic.fullName",confidence:.96,reasonCodes:["semantic_label"],candidatePaths:[{profilePath:"basic.fullName",confidence:.96},{profilePath:"basic.email",confidence:.7}],...overrides};}
function matcher(provider:FakeAIProvider){return new ProviderSemanticMatcher(provider);}
describe("Hybrid Semantic Matcher",()=>{
 it("does not call AI for a rule matched field",async()=>{const provider=new FakeAIProvider(()=>ai());const result=await hybridMatchField(field(),rule("matched"),{enabled:true,matcher:matcher(provider)});expect(provider.calls).toHaveLength(0);expect(result.source).toBe("rule");});
 it("calls AI for ambiguous",async()=>{const provider=new FakeAIProvider(()=>ai());expect((await hybridMatchField(field(),rule("ambiguous"),{enabled:true,matcher:matcher(provider)})).source).toBe("ai");expect(provider.calls).toHaveLength(1);});
 it("calls AI for unmatched",async()=>{const provider=new FakeAIProvider(()=>ai());await hybridMatchField(field(),rule("unmatched"),{enabled:true,matcher:matcher(provider)});expect(provider.calls).toHaveLength(1);});
 it("removes vetoed candidates before AI",async()=>{const provider=new FakeAIProvider(()=>({status:"unmatched",confidence:0,reasonCodes:["negative_context"],candidatePaths:[]}));const unsafe=field("紧急联系人姓名");await hybridMatchField(unsafe,rule("unmatched"),{enabled:true,matcher:matcher(provider)});expect(provider.calls[0].availableProfilePaths).not.toContain("basic.fullName");expect(provider.calls[0].candidates.map(item=>item.profilePath)).not.toContain("basic.fullName");});
 it("rejects an illegal profile path",async()=>{const provider=new FakeAIProvider(()=>({...ai(),profilePath:"private.secret",candidatePaths:[{profilePath:"private.secret",confidence:.99}]}));const result=await hybridMatchField(field(),rule(),{enabled:true,matcher:matcher(provider)});expect(result.aiStatus).toBe("failed");expect(result.failureReason).toBe("invalid_response");});
 it("keeps low AI confidence ambiguous",async()=>{const provider=new FakeAIProvider(()=>ai({confidence:.82,candidatePaths:[{profilePath:"basic.fullName",confidence:.82}]}));const result=await hybridMatchField(field(),rule(),{enabled:true,matcher:matcher(provider)});expect(result.hybridResult.status).toBe("ambiguous");});
 it("keeps a small candidate margin ambiguous",async()=>{const provider=new FakeAIProvider(()=>ai({candidatePaths:[{profilePath:"basic.fullName",confidence:.96},{profilePath:"basic.email",confidence:.9}]}));expect((await hybridMatchField(field(),rule(),{enabled:true,matcher:matcher(provider)})).hybridResult.status).toBe("ambiguous");});
 it("falls back on provider error",async()=>{const provider=new FakeAIProvider(()=>{throw new Error("provider down");});const original=rule();const result=await hybridMatchField(field(),original,{enabled:true,matcher:matcher(provider)});expect(result.hybridResult).toBe(original);expect(result.failureReason).toBe("provider_error");});
 it("falls back on timeout",async()=>{const provider=new FakeAIProvider(()=>new Promise(resolve=>setTimeout(()=>resolve(ai()),30)));const result=await hybridMatchField(field(),rule(),{enabled:true,matcher:matcher(provider),timeoutMs:2});expect(result.failureReason).toBe("timeout");});
 it("falls back on malformed response",async()=>{const provider=new FakeAIProvider(()=>"not-json");const result=await hybridMatchField(field(),rule(),{enabled:true,matcher:matcher(provider)});expect(result.failureReason).toBe("invalid_response");});
 it("does not preselect AI matched suggestions",async()=>{const original=rule("ambiguous");const provider=new FakeAIProvider(()=>ai());const hybrid=await hybridMatchField(field(),original,{enabled:true,matcher:matcher(provider)});expect(defaultSelectedFieldIds([original],new Map([["f1",hybrid]]))).not.toContain("f1");expect(hybrid.requiresHumanConfirmation).toBe(true);});
 it("semantic input contains structure but no profile values",()=>{const input=createSemanticInput(field(),rule());const json=JSON.stringify(input);expect(json).toContain("Candidate name");expect(json).not.toContain("currentValue");expect(json).not.toContain("userProfile");});
 it("uses cache without a repeated provider call",async()=>{const provider=new FakeAIProvider(()=>ai());const cache=new SemanticMatchCache();await hybridMatchField(field(),rule(),{enabled:true,matcher:matcher(provider),cache});const second=await hybridMatchField(field(),rule(),{enabled:true,matcher:matcher(provider),cache});expect(provider.calls).toHaveLength(1);expect(second.aiStatus).toBe("cache_hit");});
 it("never calls a provider while AI is disabled",async()=>{const provider=new FakeAIProvider(()=>ai());const result=await hybridMatchField(field(),rule(),{enabled:false,matcher:matcher(provider)});expect(provider.calls).toHaveLength(0);expect(result.hybridResult).toEqual(result.ruleResult);});
 it("does not call AI for excluded fields",async()=>{const provider=new FakeAIProvider(()=>ai());const excluded=field();excluded.safety.excluded=true;await hybridMatchField(excluded,rule(),{enabled:true,matcher:matcher(provider)});expect(provider.calls).toHaveLength(0);});
 it("validates confidence bounds",async()=>{const provider=new FakeAIProvider(()=>ai({confidence:1.2}));expect((await hybridMatchField(field(),rule(),{enabled:true,matcher:matcher(provider)})).failureReason).toBe("invalid_response");});
 it("registers providers without allowing duplicate IDs",()=>{const registry=new AIProviderRegistry();const provider=new FakeAIProvider(()=>ai());registry.register(provider);expect(registry.get("fake")).toBe(provider);expect(()=>registry.register(provider)).toThrow("duplicate_ai_provider");registry.unregister("fake");expect(registry.list()).toEqual([]);});
});